// The request for dashboard to get the models

var request = {
	"method": "getModels",
	"type": "request",
    "parameters": {
    	"kpiList": ['kpi1'] // optional filter to get models only 
    }
}

// The reponse from a model to show itself in the dashboard

var response = {
  "method": "getModels",
  "type": "response",
  "name": "My Model",
  "id": "myModel",
  "description": "My description about the model",
  "kpiList": ["kpi1"] // this is mandatory and will connect the model to these kpis in the dashboard, normally you only deliver one kpi
  // the registered kpis exists in the dashboard database and are available in the application 
  // kpi.alias is the property to hook the model to, it is generated by kpi.name -> toLowerCase() -> split(' ').join('-') 
}

